package cs211.project.controllers.login;

import javafx.fxml.FXML;
import javafx.scene.control.Label;

/**
 * This is a sample controller, generated by IntelliJ, not need in your project.
 */
public class LoginController {
    @FXML
    private Label welcomeText;

    @FXML
    protected void onHelloButtonClick() {
        welcomeText.setText("Welcome to JavaFX Application!");
    }
}